# Generated by Django 3.0.3 on 2020-02-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='question',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
