# Generated by Django 3.0.3 on 2020-03-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythyAPI', '0004_auto_20200301_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(default='0', max_length=50)),
                ('place', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=5)),
                ('timein', models.CharField(max_length=20)),
            ],
        ),
    ]
