# Generated by Django 3.0.3 on 2020-03-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythyAPI', '0008_auto_20200302_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
